
import os
import datetime
import re
import random

BLOG_DIR = "/Users/mac/code/super-individual/projects/seo-site/src/content/blog"
FALLBACK_IMAGE = "/assets/blog-fallback.jpg"

def slugify(text):
    text = text.lower().strip()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_-]+', '-', text)
    text = re.sub(r'^-+|-+$', '', text)
    return text

def get_templates(keyword, summary):
    # Template 1: Technical/Security Focus
    t1 = f"""## Security & Access Brief: The {keyword.title()} Protocol

We have analyzed the breakout behavior of **{keyword}**. Unlike standard search updates, this shift impacts the **Machine Access** layer of your infrastructure. 

### Why {keyword} Triggers an Audit

If your robots.txt or agents.txt files aren't calibrated for the logic used by {keyword}, your high-value content becomes "dark data"—invisible to the very engines that generate modern search traffic.

### Technical Analysis
{summary}

### Tactical Response
- **Machine Access Validation**: Ensure no legacy firewall rules are blocking the user-agents associated with {keyword}. Run a [Full Visibility Audit](/tools/aeo-audit).
- **Entity Identification**: Use Schema.json to define your relationship with the concepts {keyword} interprets.
"""

    # Template 2: RAG & Context Focus
    t2 = f"""## Knowledge Layer Intelligence: Optimizing for {keyword.title()}

The emergence of **{keyword}** marks a pivot in the **Knowledge Layer** of the web. This model prioritizes **RAG (Retrieval-Augmented Generation)** over traditional link-based ranking.

### How {keyword} Synthesizes Data
{summary}

### GEO (Generative Engine Optimization) Tips
1. **Clean Context**: Use `llms.txt` to provide a noise-free version of your site for {keyword}.
2. **Citation Readiness**: Structure your claims so they are easily cited by AI models.
3. **Visibility Check**: Verify your semantic graph using our [AI Diagnostic Tool](/tools/aeo-audit).
"""

    # Template 3: Market & Trend Focus
    t3 = f"""## Market Pulse: The {keyword.title()} GEO Narrative

The search interest spike in **{keyword}** isn't just news; it's a structural change in the **Entity Graph**. We are tracking how {keyword.title()} changes user expectations for real-time answers.

### Intelligence Breakdown
{summary}

### Strategic Recommendations
- **Dynamic Content**: Ensure your content frequency matches the velocity of {keyword.title()}'s indexing.
- **RAG Anchor**: Create deep, data-rich subpages for concepts {keyword} is currently exploring.
- **Run Diagnostics**: Check your site's adaptability using our [GEO Scanner](/tools/aeo-audit).
"""

    return [t1, t2, t3]

def generate_faq(keyword):
    faqs = [
        f"**Q: How does {keyword} affect my current SEO ranking?**\n*A: While traditional ranking might stay stable, your 'Citation Rate' in AI-generated answers will fluctuate depending on your Knowledge Layer optimization.*",
        f"**Q: Should I block {keyword}'s crawler?**\n*A: Only if you want to protect training data. For visibility, we recommend an 'Explicit Allow' strategy with a clean llms.txt entry.*",
        f"**Q: Is {keyword} compatible with standard Schema.org?**\n*A: Yes, but it prioritizes nested JSON-LD that defines clear entity relationships over simple flat tags.*"
    ]
    random.shuffle(faqs)
    return "\n\n### GEO Frequently Asked Questions\n" + "\n".join(faqs)

def generate_trend_post(keyword, analysis_summary):
    date_str = datetime.datetime.now().strftime("%b %d %Y")
    year = datetime.datetime.now().year
    slug = f"{slugify(keyword)}-{year}"
    filepath = os.path.join(BLOG_DIR, f"{slug}.md")
    
    # Randomly select a template to ensure structural diversity
    templates = get_templates(keyword, analysis_summary)
    main_content = random.choice(templates)
    faq_content = generate_faq(keyword)
    
    # Dynamic titles and descriptions
    titles = [
        f"GEO Intelligence: Why {keyword.title()} is a Breakout Threat",
        f"Does {keyword.title()} Kill Traditional SEO? A Deep Dive",
        f"AEO Audit: Getting Your Site Ready for {keyword.title()}",
        f"The {keyword.title()} Protocol: A Guide for Site Owners"
    ]
    
    title = random.choice(titles)
    description = f"Critical analysis of {keyword}. Discover how this specific AI trend impacts search visibility and citation rates."
    
    content = f"""---
title: "{title}"
description: "{description}"
pubDate: "{date_str}"
heroImage: "{FALLBACK_IMAGE}"
---

{main_content}

{faq_content}

---
*Generated by Sentinel Scout V2 - High-Diversity GEO Monitoring.*
"""
    
    with os.fdopen(os.open(filepath, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644), 'w') as f:
        f.write(content)
    print(f"Refactored with V2 Diversity: {keyword}")

if __name__ == "__main__":
    snap_trends = [
        ("manus ai", "Manus AI's agentic navigation means your site's 'Actionability' score is now a ranking factor. Ensure your UI buttons and API endpoints are clearly labeled for machine interpretation."),
        ("higgsfield ai", "Higgsfield moves video generation into the mainstream. SEO is no longer just text; you need ALT-text for video frames and semantic video metadata to be cited in generative video search."),
        ("veo 3 ai", "Google's Veo 3 integration in Search Labs means video-first results. Your site must provide high-quality, frame-level descriptions to be featured in the AI-generated video panel."),
        ("lmarena ai", "LM Arena (Chatbot Arena) trends indicate a shift in user trust. Being mentioned in the system prompts or training datasets of top-ranked models is the ultimate AEO goal."),
        ("ai news today", "This high-volume gateway term is your chance to capture traffic. Use it to funnel users into specific 'AI Visibility' audits before they get lost in mainstream noise."),
        ("openai news today", "Direct traffic from OpenAI product updates is high-value. Align your content structure with the latest Markdown support in o1/o3 models."),
        ("lovable ai", "Lovable is changing the barrier to startup creation. SEO for the software-gen era means documenting component APIs, not just selling services."),
        ("grok 3 ai", "Elon's Grok 3 will have deep X-integration. Real-time data signals and social velocity are now ranking factors for GEO."),
        ("deepseek", "The rise of DeepSeek highlights the decentralization of intelligence. Optimizing for non-western models is becoming a strategic necessity for global visibility."),
        ("qwen ai", "Alibaba's Qwen is dominant in Asian markets. If you are targeting that region, your AEO must comply with domestic China AI safety standards."),
        ("agentic ai", "The shift from search to 'agents' means you are no longer ranking for human users, but for agents choosing which tool to use."),
        ("notebooklm", "NotebookLM is essentially a localized RAG. If your PDFs aren't clean (header-first structure), NotebookLM won't summarize you correctly."),
        ("gemini ai", "Gemini's 2M context window means it reads everything. You can no longer hide low-quality content at the bottom of the page.")
    ]
    
    for kw, summary in snap_trends:
        generate_trend_post(kw, summary)
